server:
  port: 20000
  address: localhost

spring:
  application:
    name: logging

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 21000

eureka:
  instance:
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
    prefer-ip-address: true
    metadataMap:
       management.port: ${management.server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    ROOT: ERROR
    at: DEBUG